import Head from 'next/head';

export const metadata = {
  title: 'UNERG',
  description: 'Generated by Next.js',
  favicon: '/favicon.ico'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
        <link rel="icon" href={metadata.favicon} />
      </Head>
      <body>
        {children}
      </body>
    </html>
  );
}

